name: dusk
on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev
env:
  APP_ENV: testing
  APP_URL: "http://127.0.0.1:8000"
  DB_PORT: ${{ job.services.mariadb.ports['3306'] }}
  STRIPE_API_BASE: "127.0.0.1:${{ job.services.localstripe.ports[8420] }}"
  DUSK_DRIVER_URL: "http://127.0.0.1:9515"
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1        
  DB_DATABASE: db
  DB_USERNAME: root
  DB_PASSWORD: ""

jobs:
  dusk:
    runs-on: ubuntu-latest

    name: PHP Dusk    
    services:
      localstripe:
        image: adrienverge/localstripe:latest
        ports:
          - 8420
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db          
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Prepare the application
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Clear Config
      run: |
        php artisan config:clear
        php artisan cache:clear
        php artisan route:clear
        php artisan event:clear
        php artisan view:clear

    - name: Run Migration
      run: php artisan migrate --force
      env:
        DB_PORT: ${{ job.services.mariadb.ports['3306'] }}

    - name: Run DB Seed
      run: php artisan db:seed
      env:
        DB_PORT: ${{ job.services.mariadb.ports['3306'] }}

    - name: Build NPM Assets
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Complile Assets
      env:
        NODE_ENV: development
      run: |
        npm ci
        npm run build

    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`

    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux &

    - name: Run Laravel Server
      run: php artisan serve --no-reload &

    - name: Run Dusk Tests
      run: php artisan dusk

    - name: Upload Screenshots
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: tests/Browser/screenshots

    - name: Upload Console Logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: console
        path: tests/Browser/console
