name: phpDocumentor

on:
  pull_request:
    branches: 
      - dev      

jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run phpdoc
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -d ./app -t ./Docs

      - name: git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git add Docs/
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git push