<?php

namespace App\Core;

use function PHPSTORM_META\map;

class Data
{
    public static function getCountriesList()
    {
        return [
            'AF' => ['name' => 'Afghanistan', 'flag' => 'flags/afghanistan.svg'],
            'AX' => ['name' => 'Aland Islands', 'flag' => 'flags/aland-islands.svg'],
            'AL' => ['name' => 'Albania', 'flag' => 'flags/albania.svg'],
            'DZ' => ['name' => 'Algeria', 'flag' => 'flags/algeria.svg'],
            'AS' => ['name' => 'American Samoa', 'flag' => 'flags/american-samoa.svg'],
            'AD' => ['name' => 'Andorra', 'flag' => 'flags/andorra.svg'],
            'AO' => ['name' => 'Angola', 'flag' => 'flags/angola.svg'],
            'AI' => ['name' => 'Anguilla', 'flag' => 'flags/anguilla.svg'],
            'AG' => ['name' => 'Antigua and Barbuda', 'flag' => 'flags/antigua-and-barbuda.svg'],
            'AR' => ['name' => 'Argentina', 'flag' => 'flags/argentina.svg'],
            'AM' => ['name' => 'Armenia', 'flag' => 'flags/armenia.svg'],
            'AW' => ['name' => 'Aruba', 'flag' => 'flags/aruba.svg'],
            'AU' => ['name' => 'Australia', 'flag' => 'flags/australia.svg'],
            'AT' => ['name' => 'Austria', 'flag' => 'flags/austria.svg'],
            'AZ' => ['name' => 'Azerbaijan', 'flag' => 'flags/azerbaijan.svg'],
            'BS' => ['name' => 'Bahamas', 'flag' => 'flags/bahamas.svg'],
            'BH' => ['name' => 'Bahrain', 'flag' => 'flags/bahrain.svg'],
            'BD' => ['name' => 'Bangladesh', 'flag' => 'flags/bangladesh.svg'],
            'BB' => ['name' => 'Barbados', 'flag' => 'flags/barbados.svg'],
            'BY' => ['name' => 'Belarus', 'flag' => 'flags/belarus.svg'],
            'BE' => ['name' => 'Belgium', 'flag' => 'flags/belgium.svg'],
            'BZ' => ['name' => 'Belize', 'flag' => 'flags/belize.svg'],
            'BJ' => ['name' => 'Benin', 'flag' => 'flags/benin.svg'],
            'BM' => ['name' => 'Bermuda', 'flag' => 'flags/bermuda.svg'],
            'BT' => ['name' => 'Bhutan', 'flag' => 'flags/bhutan.svg'],
            'BO' => ['name' => 'Bolivia, Plurinational State of', 'flag' => 'flags/bolivia.svg'],
            'BQ' => ['name' => 'Bonaire, Sint Eustatius and Saba', 'flag' => 'flags/bonaire.svg'],
            'BA' => ['name' => 'Bosnia and Herzegovina', 'flag' => 'flags/bosnia-and-herzegovina.svg'],
            'BW' => ['name' => 'Botswana', 'flag' => 'flags/botswana.svg'],
            'BR' => ['name' => 'Brazil', 'flag' => 'flags/brazil.svg'],
            'IO' => ['name' => 'British Indian Ocean Territory', 'flag' => 'flags/british-indian-ocean-territory.svg'],
            'BN' => ['name' => 'Brunei Darussalam', 'flag' => 'flags/brunei.svg'],
            'BG' => ['name' => 'Bulgaria', 'flag' => 'flags/bulgaria.svg'],
            'BF' => ['name' => 'Burkina Faso', 'flag' => 'flags/burkina-faso.svg'],
            'BI' => ['name' => 'Burundi', 'flag' => 'flags/burundi.svg'],
            'KH' => ['name' => 'Cambodia', 'flag' => 'flags/cambodia.svg'],
            'CM' => ['name' => 'Cameroon', 'flag' => 'flags/cameroon.svg'],
            'CA' => ['name' => 'Canada', 'flag' => 'flags/canada.svg'],
            'CV' => ['name' => 'Cape Verde', 'flag' => 'flags/cape-verde.svg'],
            'KY' => ['name' => 'Cayman Islands', 'flag' => 'flags/cayman-islands.svg'],
            'CF' => ['name' => 'Central African Republic', 'flag' => 'flags/central-african-republic.svg'],
            'TD' => ['name' => 'Chad', 'flag' => 'flags/chad.svg'],
            'CL' => ['name' => 'Chile', 'flag' => 'flags/chile.svg'],
            'CN' => ['name' => 'China', 'flag' => 'flags/china.svg'],
            'CX' => ['name' => 'Christmas Island', 'flag' => 'flags/christmas-island.svg'],
            'CC' => ['name' => 'Cocos (Keeling) Islands', 'flag' => 'flags/cocos-island.svg'],
            'CO' => ['name' => 'Colombia', 'flag' => 'flags/colombia.svg'],
            'KM' => ['name' => 'Comoros', 'flag' => 'flags/comoros.svg'],
            'CK' => ['name' => 'Cook Islands', 'flag' => 'flags/cook-islands.svg'],
            'CR' => ['name' => 'Costa Rica', 'flag' => 'flags/costa-rica.svg'],
            'CI' => ['name' => 'Côte d\'Ivoire', 'flag' => 'flags/ivory-coast.svg'],
            'HR' => ['name' => 'Croatia', 'flag' => 'flags/croatia.svg'],
            'CU' => ['name' => 'Cuba', 'flag' => 'flags/cuba.svg'],
            'CW' => ['name' => 'Curaçao', 'flag' => 'flags/curacao.svg'],
            'CZ' => ['name' => 'Czech Republic', 'flag' => 'flags/czech-republic.svg'],
            'DK' => ['name' => 'Denmark', 'flag' => 'flags/denmark.svg'],
            'DJ' => ['name' => 'Djibouti', 'flag' => 'flags/djibouti.svg'],
            'DM' => ['name' => 'Dominica', 'flag' => 'flags/dominica.svg'],
            'DO' => ['name' => 'Dominican Republic', 'flag' => 'flags/dominican-republic.svg'],
            'EC' => ['name' => 'Ecuador', 'flag' => 'flags/ecuador.svg'],
            'EG' => ['name' => 'Egypt', 'flag' => 'flags/egypt.svg'],
            'SV' => ['name' => 'El Salvador', 'flag' => 'flags/el-salvador.svg'],
            'GQ' => ['name' => 'Equatorial Guinea', 'flag' => 'flags/equatorial-guinea.svg'],
            'ER' => ['name' => 'Eritrea', 'flag' => 'flags/eritrea.svg'],
            'EE' => ['name' => 'Estonia', 'flag' => 'flags/estonia.svg'],
            'ET' => ['name' => 'Ethiopia', 'flag' => 'flags/ethiopia.svg'],
            'FK' => ['name' => 'Falkland Islands (Malvinas)', 'flag' => 'flags/falkland-islands.svg'],
            'FJ' => ['name' => 'Fiji', 'flag' => 'flags/fiji.svg'],
            'FI' => ['name' => 'Finland', 'flag' => 'flags/finland.svg'],
            'FR' => ['name' => 'France', 'flag' => 'flags/france.svg'],
            'PF' => ['name' => 'French Polynesia', 'flag' => 'flags/french-polynesia.svg'],
            'GA' => ['name' => 'Gabon', 'flag' => 'flags/gabon.svg'],
            'GM' => ['name' => 'Gambia', 'flag' => 'flags/gambia.svg'],
            'GE' => ['name' => 'Georgia', 'flag' => 'flags/georgia.svg'],
            'DE' => ['name' => 'Germany', 'flag' => 'flags/germany.svg'],
            'GH' => ['name' => 'Ghana', 'flag' => 'flags/ghana.svg'],
            'GI' => ['name' => 'Gibraltar', 'flag' => 'flags/gibraltar.svg'],
            'GR' => ['name' => 'Greece', 'flag' => 'flags/greece.svg'],
            'GL' => ['name' => 'Greenland', 'flag' => 'flags/greenland.svg'],
            'GD' => ['name' => 'Grenada', 'flag' => 'flags/grenada.svg'],
            'GU' => ['name' => 'Guam', 'flag' => 'flags/guam.svg'],
            'GT' => ['name' => 'Guatemala', 'flag' => 'flags/guatemala.svg'],
            'GG' => ['name' => 'Guernsey', 'flag' => 'flags/guernsey.svg'],
            'GN' => ['name' => 'Guinea', 'flag' => 'flags/guinea.svg'],
            'GW' => ['name' => 'Guinea-Bissau', 'flag' => 'flags/guinea-bissau.svg'],
            'HT' => ['name' => 'Haiti', 'flag' => 'flags/haiti.svg'],
            'VA' => ['name' => 'Holy See (Vatican City State)', 'flag' => 'flags/vatican-city.svg'],
            'HN' => ['name' => 'Honduras', 'flag' => 'flags/honduras.svg'],
            'HK' => ['name' => 'Hong Kong', 'flag' => 'flags/hong-kong.svg'],
            'HU' => ['name' => 'Hungary', 'flag' => 'flags/hungary.svg'],
            'IS' => ['name' => 'Iceland', 'flag' => 'flags/iceland.svg'],
            'IN' => ['name' => 'India', 'flag' => 'flags/india.svg'],
            'ID' => ['name' => 'Indonesia', 'flag' => 'flags/indonesia.svg'],
            'IR' => ['name' => 'Iran, Islamic Republic of', 'flag' => 'flags/iran.svg'],
            'IQ' => ['name' => 'Iraq', 'flag' => 'flags/iraq.svg'],
            'IE' => ['name' => 'Ireland', 'flag' => 'flags/ireland.svg'],
            'IM' => ['name' => 'Isle of Man', 'flag' => 'flags/isle-of-man.svg'],
            'IL' => ['name' => 'Israel', 'flag' => 'flags/israel.svg'],
            'IT' => ['name' => 'Italy', 'flag' => 'flags/italy.svg'],
            'JM' => ['name' => 'Jamaica', 'flag' => 'flags/jamaica.svg'],
            'JP' => ['name' => 'Japan', 'flag' => 'flags/japan.svg'],
            'JE' => ['name' => 'Jersey', 'flag' => 'flags/jersey.svg'],
            'JO' => ['name' => 'Jordan', 'flag' => 'flags/jordan.svg'],
            'KZ' => ['name' => 'Kazakhstan', 'flag' => 'flags/kazakhstan.svg'],
            'KE' => ['name' => 'Kenya', 'flag' => 'flags/kenya.svg'],
            'KI' => ['name' => 'Kiribati', 'flag' => 'flags/kiribati.svg'],
            'KP' => ['name' => 'Korea, Democratic People\'s Republic of', 'flag' => 'flags/north-korea.svg'],
            'KW' => ['name' => 'Kuwait', 'flag' => 'flags/kuwait.svg'],
            'KG' => ['name' => 'Kyrgyzstan', 'flag' => 'flags/kyrgyzstan.svg'],
            'LA' => ['name' => 'Lao People\'s Democratic Republic', 'flag' => 'flags/laos.svg'],
            'LV' => ['name' => 'Latvia', 'flag' => 'flags/latvia.svg'],
            'LB' => ['name' => 'Lebanon', 'flag' => 'flags/lebanon.svg'],
            'LS' => ['name' => 'Lesotho', 'flag' => 'flags/lesotho.svg'],
            'LR' => ['name' => 'Liberia', 'flag' => 'flags/liberia.svg'],
            'LY' => ['name' => 'Libya', 'flag' => 'flags/libya.svg'],
            'LI' => ['name' => 'Liechtenstein', 'flag' => 'flags/liechtenstein.svg'],
            'LT' => ['name' => 'Lithuania', 'flag' => 'flags/lithuania.svg'],
            'LU' => ['name' => 'Luxembourg', 'flag' => 'flags/luxembourg.svg'],
            'MO' => ['name' => 'Macao', 'flag' => 'flags/macao.svg'],
            'MG' => ['name' => 'Madagascar', 'flag' => 'flags/madagascar.svg'],
            'MW' => ['name' => 'Malawi', 'flag' => 'flags/malawi.svg'],
            'MY' => ['name' => 'Malaysia', 'flag' => 'flags/malaysia.svg'],
            'MV' => ['name' => 'Maldives', 'flag' => 'flags/maldives.svg'],
            'ML' => ['name' => 'Mali', 'flag' => 'flags/mali.svg'],
            'MT' => ['name' => 'Malta', 'flag' => 'flags/malta.svg'],
            'MH' => ['name' => 'Marshall Islands', 'flag' => 'flags/marshall-island.svg'],
            'MQ' => ['name' => 'Martinique', 'flag' => 'flags/martinique.svg'],
            'MR' => ['name' => 'Mauritania', 'flag' => 'flags/mauritania.svg'],
            'MU' => ['name' => 'Mauritius', 'flag' => 'flags/mauritius.svg'],
            'MX' => ['name' => 'Mexico', 'flag' => 'flags/mexico.svg'],
            'FM' => ['name' => 'Micronesia, Federated States of', 'flag' => 'flags/micronesia.svg'],
            'MD' => ['name' => 'Moldova, Republic of', 'flag' => 'flags/moldova.svg'],
            'MC' => ['name' => 'Monaco', 'flag' => 'flags/monaco.svg'],
            'MN' => ['name' => 'Mongolia', 'flag' => 'flags/mongolia.svg'],
            'ME' => ['name' => 'Montenegro', 'flag' => 'flags/montenegro.svg'],
            'MS' => ['name' => 'Montserrat', 'flag' => 'flags/montserrat.svg'],
            'MA' => ['name' => 'Morocco', 'flag' => 'flags/morocco.svg'],
            'MZ' => ['name' => 'Mozambique', 'flag' => 'flags/mozambique.svg'],
            'MM' => ['name' => 'Myanmar', 'flag' => 'flags/myanmar.svg'],
            'NA' => ['name' => 'Namibia', 'flag' => 'flags/namibia.svg'],
            'NR' => ['name' => 'Nauru', 'flag' => 'flags/nauru.svg'],
            'NP' => ['name' => 'Nepal', 'flag' => 'flags/nepal.svg'],
            'NL' => ['name' => 'Netherlands', 'flag' => 'flags/netherlands.svg'],
            'NZ' => ['name' => 'New Zealand', 'flag' => 'flags/new-zealand.svg'],
            'NI' => ['name' => 'Nicaragua', 'flag' => 'flags/nicaragua.svg'],
            'NE' => ['name' => 'Niger', 'flag' => 'flags/niger.svg'],
            'NG' => ['name' => 'Nigeria', 'flag' => 'flags/nigeria.svg'],
            'NU' => ['name' => 'Niue', 'flag' => 'flags/niue.svg'],
            'NF' => ['name' => 'Norfolk Island', 'flag' => 'flags/norfolk-island.svg'],
            'MP' => ['name' => 'Northern Mariana Islands', 'flag' => 'flags/northern-mariana-islands.svg'],
            'NO' => ['name' => 'Norway', 'flag' => 'flags/norway.svg'],
            'OM' => ['name' => 'Oman', 'flag' => 'flags/oman.svg'],
            'PK' => ['name' => 'Pakistan', 'flag' => 'flags/pakistan.svg'],
            'PW' => ['name' => 'Palau', 'flag' => 'flags/palau.svg'],
            'PS' => ['name' => 'Palestinian Territory, Occupied', 'flag' => 'flags/palestine.svg'],
            'PA' => ['name' => 'Panama', 'flag' => 'flags/panama.svg'],
            'PG' => ['name' => 'Papua New Guinea', 'flag' => 'flags/papua-new-guinea.svg'],
            'PY' => ['name' => 'Paraguay', 'flag' => 'flags/paraguay.svg'],
            'PE' => ['name' => 'Peru', 'flag' => 'flags/peru.svg'],
            'PH' => ['name' => 'Philippines', 'flag' => 'flags/philippines.svg'],
            'PL' => ['name' => 'Poland', 'flag' => 'flags/poland.svg'],
            'PT' => ['name' => 'Portugal', 'flag' => 'flags/portugal.svg'],
            'PR' => ['name' => 'Puerto Rico', 'flag' => 'flags/puerto-rico.svg'],
            'QA' => ['name' => 'Qatar', 'flag' => 'flags/qatar.svg'],
            'RO' => ['name' => 'Romania', 'flag' => 'flags/romania.svg'],
            'RU' => ['name' => 'Russian Federation', 'flag' => 'flags/russia.svg'],
            'RW' => ['name' => 'Rwanda', 'flag' => 'flags/rwanda.svg'],
            'BL' => ['name' => 'Saint Barthélemy', 'flag' => 'flags/st-barts.svg'],
            'KN' => ['name' => 'Saint Kitts and Nevis', 'flag' => 'flags/saint-kitts-and-nevis.svg'],
            'LC' => ['name' => 'Saint Lucia', 'flag' => 'flags/st-lucia.svg'],
            'MF' => ['name' => 'Saint Martin (French part)', 'flag' => 'flags/sint-maarten.svg'],
            // 'PM' => array('name' => 'Saint Pierre and Miquelon', 'flag' => 'flags/saint-pierre.svg'),
            'VC' => ['name' => 'Saint Vincent and the Grenadines', 'flag' => 'flags/st-vincent-and-the-grenadines.svg'],
            'WS' => ['name' => 'Samoa', 'flag' => 'flags/samoa.svg'],
            'SM' => ['name' => 'San Marino', 'flag' => 'flags/san-marino.svg'],
            'ST' => ['name' => 'Sao Tome and Principe', 'flag' => 'flags/sao-tome-and-prince.svg'],
            'SA' => ['name' => 'Saudi Arabia', 'flag' => 'flags/saudi-arabia.svg'],
            'SN' => ['name' => 'Senegal', 'flag' => 'flags/senegal.svg'],
            'RS' => ['name' => 'Serbia', 'flag' => 'flags/serbia.svg'],
            'SC' => ['name' => 'Seychelles', 'flag' => 'flags/seychelles.svg'],
            'SL' => ['name' => 'Sierra Leone', 'flag' => 'flags/sierra-leone.svg'],
            'SG' => ['name' => 'Singapore', 'flag' => 'flags/singapore.svg'],
            'SX' => ['name' => 'Sint Maarten (Dutch part)', 'flag' => 'flags/sint-maarten.svg'],
            'SK' => ['name' => 'Slovakia', 'flag' => 'flags/slovakia.svg'],
            'SI' => ['name' => 'Slovenia', 'flag' => 'flags/slovenia.svg'],
            'SB' => ['name' => 'Solomon Islands', 'flag' => 'flags/solomon-islands.svg'],
            'SO' => ['name' => 'Somalia', 'flag' => 'flags/somalia.svg'],
            'ZA' => ['name' => 'South Africa', 'flag' => 'flags/south-africa.svg'],
            'KR' => ['name' => 'South Korea', 'flag' => 'flags/south-korea.svg'],
            'SS' => ['name' => 'South Sudan', 'flag' => 'flags/south-sudan.svg'],
            'ES' => ['name' => 'Spain', 'flag' => 'flags/spain.svg'],
            'LK' => ['name' => 'Sri Lanka', 'flag' => 'flags/sri-lanka.svg'],
            'SD' => ['name' => 'Sudan', 'flag' => 'flags/sudan.svg'],
            'SR' => ['name' => 'Suriname', 'flag' => 'flags/suriname.svg'],
            'SZ' => ['name' => 'Swaziland', 'flag' => 'flags/swaziland.svg'],
            'SE' => ['name' => 'Sweden', 'flag' => 'flags/sweden.svg'],
            'CH' => ['name' => 'Switzerland', 'flag' => 'flags/switzerland.svg'],
            'SY' => ['name' => 'Syrian Arab Republic', 'flag' => 'flags/syria.svg'],
            'TW' => ['name' => 'Taiwan, Province of China', 'flag' => 'flags/taiwan.svg'],
            'TJ' => ['name' => 'Tajikistan', 'flag' => 'flags/tajikistan.svg'],
            'TZ' => ['name' => 'Tanzania, United Republic of', 'flag' => 'flags/tanzania.svg'],
            'TH' => ['name' => 'Thailand', 'flag' => 'flags/thailand.svg'],
            'TG' => ['name' => 'Togo', 'flag' => 'flags/togo.svg'],
            'TK' => ['name' => 'Tokelau', 'flag' => 'flags/tokelau.svg'],
            'TO' => ['name' => 'Tonga', 'flag' => 'flags/tonga.svg'],
            'TT' => ['name' => 'Trinidad and Tobago', 'flag' => 'flags/trinidad-and-tobago.svg'],
            'TN' => ['name' => 'Tunisia', 'flag' => 'flags/tunisia.svg'],
            'TR' => ['name' => 'Turkey', 'flag' => 'flags/turkey.svg'],
            'TM' => ['name' => 'Turkmenistan', 'flag' => 'flags/turkmenistan.svg'],
            'TC' => ['name' => 'Turks and Caicos Islands', 'flag' => 'flags/turks-and-caicos.svg'],
            'TV' => ['name' => 'Tuvalu', 'flag' => 'flags/tuvalu.svg'],
            'UG' => ['name' => 'Uganda', 'flag' => 'flags/uganda.svg'],
            'UA' => ['name' => 'Ukraine', 'flag' => 'flags/ukraine.svg'],
            'AE' => ['name' => 'United Arab Emirates', 'flag' => 'flags/united-arab-emirates.svg'],
            'GB' => ['name' => 'United Kingdom', 'flag' => 'flags/united-kingdom.svg'],
            'US' => ['name' => 'United States', 'flag' => 'flags/united-states.svg'],
            'UY' => ['name' => 'Uruguay', 'flag' => 'flags/uruguay.svg'],
            'UZ' => ['name' => 'Uzbekistan', 'flag' => 'flags/uzbekistan.svg'],
            'VU' => ['name' => 'Vanuatu', 'flag' => 'flags/vanuatu.svg'],
            'VE' => ['name' => 'Venezuela, Bolivarian Republic of', 'flag' => 'flags/venezuela.svg'],
            'VN' => ['name' => 'Vietnam', 'flag' => 'flags/vietnam.svg'],
            'VI' => ['name' => 'Virgin Islands', 'flag' => 'flags/virgin-islands.svg'],
            'YE' => ['name' => 'Yemen', 'flag' => 'flags/yemen.svg'],
            'ZM' => ['name' => 'Zambia', 'flag' => 'flags/zambia.svg'],
            'ZW' => ['name' => 'Zimbabwe', 'flag' => 'flags/zimbabwe.svg'],
        ];
    }

    public static function getLanguagesList()
    {
        $countryArr = self::getCountriesList();

        return [
            'id' => ['name' => 'Bahasa Indonesia - Indonesian', 'country' => $countryArr['ID']],
            'msa' => ['name' => 'Bahasa Melayu - Malay', 'country' => $countryArr['MY']],
            'ca' => ['name' => 'Català - Catalan', 'country' => $countryArr['CA']],
            'cs' => ['name' => 'Čeština - Czech', 'country' => $countryArr['CZ']],
            'da' => ['name' => 'Dansk - Danish', 'country' => $countryArr['NL']],
            'de' => ['name' => 'Deutsch - German', 'country' => $countryArr['DE']],
            'en' => ['name' => 'English', 'country' => $countryArr['GB']],
            'en-gb' => ['name' => 'English UK - British English', 'country' => $countryArr['GB']],
            'es' => ['name' => 'Español - Spanish', 'country' => $countryArr['ES']],
            'fil' => ['name' => 'Filipino', 'country' => $countryArr['PH']],
            'fr' => ['name' => 'Français - French', 'country' => $countryArr['FR']],
            'ga' => ['name' => 'Gaeilge - Irish (beta)', 'country' => $countryArr['GA']],
            'gl' => ['name' => 'Galego - Galician (beta)', 'country' => $countryArr['GL']],
            'hr' => ['name' => 'Hrvatski - Croatian', 'country' => $countryArr['HR']],
            'it' => ['name' => 'Italiano - Italian', 'country' => $countryArr['IT']],
            'hu' => ['name' => 'Magyar - Hungarian', 'country' => $countryArr['HU']],
            'nl' => ['name' => 'Nederlands - Dutch', 'country' => $countryArr['NL']],
            'no' => ['name' => 'Norsk - Norwegian', 'country' => $countryArr['NO']],
            'pl' => ['name' => 'Polski - Polish', 'country' => $countryArr['PL']],
            'pt' => ['name' => 'Português - Portuguese', 'country' => $countryArr['PT']],
            'ro' => ['name' => 'Română - Romanian', 'country' => $countryArr['RO']],
            'sk' => ['name' => 'Slovenčina - Slovak', 'country' => $countryArr['SK']],
            'fi' => ['name' => 'Suomi - Finnish', 'country' => $countryArr['FI']],
            'sv' => ['name' => 'Svenska - Swedish', 'country' => $countryArr['SV']],
            'vi' => ['name' => 'Tiếng Việt - Vietnamese', 'country' => $countryArr['VI']],
            'tr' => ['name' => 'Türkçe - Turkish', 'country' => $countryArr['TR']],
            'el' => ['name' => 'Ελληνικά - Greek', 'country' => $countryArr['GR']],
            'bg' => ['name' => 'Български език - Bulgarian', 'country' => $countryArr['BG']],
            'ru' => ['name' => 'Русский - Russian', 'country' => $countryArr['RU']],
            'sr' => ['name' => 'Српски - Serbian', 'country' => $countryArr['SR']],
            'uk' => ['name' => 'Українська мова - Ukrainian', 'country' => $countryArr['UA']],
            'he' => ['name' => 'עִבְרִית - Hebrew', 'country' => $countryArr['IL']],
            'ur' => ['name' => 'اردو - Urdu (beta)', 'country' => $countryArr['PK']],
            'ar' => ['name' => 'العربية - Arabic', 'country' => $countryArr['AR']],
            'fa' => ['name' => 'فارسی - Persian', 'country' => $countryArr['AR']],
            'mr' => ['name' => 'मराठी - Marathi', 'country' => $countryArr['MR']],
            'hi' => ['name' => 'हिन्दी - Hindi', 'country' => $countryArr['IN']],
            'bn' => ['name' => 'বাংলা - Bangla', 'country' => $countryArr['BD']],
            'gu' => ['name' => 'ગુજરાતી - Gujarati', 'country' => $countryArr['GU']],
            'ta' => ['name' => 'தமிழ் - Tamil', 'country' => $countryArr['IN']],
            'kn' => ['name' => 'ಕನ್ನಡ - Kannada', 'country' => $countryArr['KN']],
            'th' => ['name' => 'ภาษาไทย - Thai', 'country' => $countryArr['TH']],
            'ko' => ['name' => '한국어 - Korean', 'country' => $countryArr['KR']],
            'ja' => ['name' => '日本語 - Japanese', 'country' => $countryArr['JP']],
            'zh-cn' => ['name' => '简体中文 - Simplified Chinese', 'country' => $countryArr['CN']],
            'zh-tw' => ['name' => '繁體中文 - Traditional Chinese', 'country' => $countryArr['TW']],
        ];
    }

    public static function getCurrencyList()
    {
        $countryArr = self::getCountriesList();

        return [
            'USD' => ['name' => 'USA dollar', 'country' => $countryArr['US']],
            'GBP' => ['name' => 'British pound', 'country' => $countryArr['GB']],
            'AUD' => ['name' => 'Australian dollar', 'country' => $countryArr['AU']],
            'JPY' => ['name' => 'Japanese yen', 'country' => $countryArr['JP']],
            'SEK' => ['name' => 'Swedish krona', 'country' => $countryArr['SE']],
            'CAD' => ['name' => 'Canadian dollar', 'country' => $countryArr['CA']],
            'CHF' => ['name' => 'Swiss franc', 'country' => $countryArr['CH']],
        ];
    }

    public static function getTimeZonesList()
    {
        return [
            'International Date Line West' => ['name' => '(GMT-11:00) International Date Line West', 'offset' => '-39600'],
            'Midway Island' => ['name' => '(GMT-11:00) Midway Island', 'offset' => '-39600'],
            'Samoa' => ['name' => '(GMT-11:00) Samoa', 'offset' => '-39600'],
            'Hawaii' => ['name' => '(GMT-10:00) Hawaii', 'offset' => '-36000'],
            'Alaska' => ['name' => '(GMT-08:00) Alaska', 'offset' => '-28800'],
            'Pacific Time (US & Canada)' => ['name' => '(GMT-07:00) Pacific Time (US & Canada)', 'offset' => '-25200'],
            'Tijuana' => ['name' => '(GMT-07:00) Tijuana', 'offset' => '-25200'],
            'Arizona' => ['name' => '(GMT-07:00) Arizona', 'offset' => '-25200'],
            'Mountain Time (US & Canada)' => ['name' => '(GMT-06:00) Mountain Time (US & Canada)', 'offset' => '-21600'],
            'Chihuahua' => ['name' => '(GMT-06:00) Chihuahua', 'offset' => '-21600'],
            'Mazatlan' => ['name' => '(GMT-06:00) Mazatlan', 'offset' => '-21600'],
            'Saskatchewan' => ['name' => '(GMT-06:00) Saskatchewan', 'offset' => '-21600'],
            'Central America' => ['name' => '(GMT-06:00) Central America', 'offset' => '-21600'],
            'Central Time (US & Canada)' => ['name' => '(GMT-05:00) Central Time (US & Canada)', 'offset' => '-18000'],
            'Guadalajara' => ['name' => '(GMT-05:00) Guadalajara', 'offset' => '-18000'],
            'Mexico City' => ['name' => '(GMT-05:00) Mexico City', 'offset' => '-18000'],
            'Monterrey' => ['name' => '(GMT-05:00) Monterrey', 'offset' => '-18000'],
            'Bogota' => ['name' => '(GMT-05:00) Bogota', 'offset' => '-18000'],
            'Lima' => ['name' => '(GMT-05:00) Lima', 'offset' => '-18000'],
            'Quito' => ['name' => '(GMT-05:00) Quito', 'offset' => '-18000'],
            'Eastern Time (US & Canada)' => ['name' => '(GMT-04:00) Eastern Time (US & Canada)', 'offset' => '-14400'],
            'Indiana (East)' => ['name' => '(GMT-04:00) Indiana (East)', 'offset' => '-14400'],
            'Caracas' => ['name' => '(GMT-04:00) Caracas', 'offset' => '-14400'],
            'La Paz' => ['name' => '(GMT-04:00) La Paz', 'offset' => '-14400'],
            'Georgetown' => ['name' => '(GMT-04:00) Georgetown', 'offset' => '-14400'],
            'Atlantic Time (Canada)' => ['name' => '(GMT-03:00) Atlantic Time (Canada)', 'offset' => '-10800'],
            'Santiago' => ['name' => '(GMT-03:00) Santiago', 'offset' => '-10800'],
            'Brasilia' => ['name' => '(GMT-03:00) Brasilia', 'offset' => '-10800'],
            'Buenos Aires' => ['name' => '(GMT-03:00) Buenos Aires', 'offset' => '-10800'],
            'Newfoundland' => ['name' => '(GMT-02:30) Newfoundland', 'offset' => '-9000'],
            'Greenland' => ['name' => '(GMT-02:00) Greenland', 'offset' => '-7200'],
            'Mid-Atlantic' => ['name' => '(GMT-02:00) Mid-Atlantic', 'offset' => '-7200'],
            'Cape Verde Is.' => ['name' => '(GMT-01:00) Cape Verde Is.', 'offset' => '-3600'],
            'Azores' => ['name' => '(GMT) Azores', 'offset' => '0'],
            'Monrovia' => ['name' => '(GMT) Monrovia', 'offset' => '0'],
            'UTC' => ['name' => '(GMT) UTC', 'offset' => '0'],
            'Dublin' => ['name' => '(GMT+01:00) Dublin', 'offset' => '3600'],
            'Edinburgh' => ['name' => '(GMT+01:00) Edinburgh', 'offset' => '3600'],
            'Lisbon' => ['name' => '(GMT+01:00) Lisbon', 'offset' => '3600'],
            'London' => ['name' => '(GMT+01:00) London', 'offset' => '3600'],
            'Casablanca' => ['name' => '(GMT+01:00) Casablanca', 'offset' => '3600'],
            'West Central Africa' => ['name' => '(GMT+01:00) West Central Africa', 'offset' => '3600'],
            'Belgrade' => ['name' => '(GMT+02:00) Belgrade', 'offset' => '7200'],
            'Bratislava' => ['name' => '(GMT+02:00) Bratislava', 'offset' => '7200'],
            'Budapest' => ['name' => '(GMT+02:00) Budapest', 'offset' => '7200'],
            'Ljubljana' => ['name' => '(GMT+02:00) Ljubljana', 'offset' => '7200'],
            'Prague' => ['name' => '(GMT+02:00) Prague', 'offset' => '7200'],
            'Sarajevo' => ['name' => '(GMT+02:00) Sarajevo', 'offset' => '7200'],
            'Skopje' => ['name' => '(GMT+02:00) Skopje', 'offset' => '7200'],
            'Warsaw' => ['name' => '(GMT+02:00) Warsaw', 'offset' => '7200'],
            'Zagreb' => ['name' => '(GMT+02:00) Zagreb', 'offset' => '7200'],
            'Brussels' => ['name' => '(GMT+02:00) Brussels', 'offset' => '7200'],
            'Copenhagen' => ['name' => '(GMT+02:00) Copenhagen', 'offset' => '7200'],
            'Madrid' => ['name' => '(GMT+02:00) Madrid', 'offset' => '7200'],
            'Paris' => ['name' => '(GMT+02:00) Paris', 'offset' => '7200'],
            'Amsterdam' => ['name' => '(GMT+02:00) Amsterdam', 'offset' => '7200'],
            'Berlin' => ['name' => '(GMT+02:00) Berlin', 'offset' => '7200'],
            'Bern' => ['name' => '(GMT+02:00) Bern', 'offset' => '7200'],
            'Rome' => ['name' => '(GMT+02:00) Rome', 'offset' => '7200'],
            'Stockholm' => ['name' => '(GMT+02:00) Stockholm', 'offset' => '7200'],
            'Vienna' => ['name' => '(GMT+02:00) Vienna', 'offset' => '7200'],
            'Cairo' => ['name' => '(GMT+02:00) Cairo', 'offset' => '7200'],
            'Harare' => ['name' => '(GMT+02:00) Harare', 'offset' => '7200'],
            'Pretoria' => ['name' => '(GMT+02:00) Pretoria', 'offset' => '7200'],
            'Bucharest' => ['name' => '(GMT+03:00) Bucharest', 'offset' => '10800'],
            'Helsinki' => ['name' => '(GMT+03:00) Helsinki', 'offset' => '10800'],
            'Kiev' => ['name' => '(GMT+03:00) Kiev', 'offset' => '10800'],
            'Kyiv' => ['name' => '(GMT+03:00) Kyiv', 'offset' => '10800'],
            'Riga' => ['name' => '(GMT+03:00) Riga', 'offset' => '10800'],
            'Sofia' => ['name' => '(GMT+03:00) Sofia', 'offset' => '10800'],
            'Tallinn' => ['name' => '(GMT+03:00) Tallinn', 'offset' => '10800'],
            'Vilnius' => ['name' => '(GMT+03:00) Vilnius', 'offset' => '10800'],
            'Athens' => ['name' => '(GMT+03:00) Athens', 'offset' => '10800'],
            'Istanbul' => ['name' => '(GMT+03:00) Istanbul', 'offset' => '10800'],
            'Minsk' => ['name' => '(GMT+03:00) Minsk', 'offset' => '10800'],
            'Jerusalem' => ['name' => '(GMT+03:00) Jerusalem', 'offset' => '10800'],
            'Moscow' => ['name' => '(GMT+03:00) Moscow', 'offset' => '10800'],
            'St. Petersburg' => ['name' => '(GMT+03:00) St. Petersburg', 'offset' => '10800'],
            'Volgograd' => ['name' => '(GMT+03:00) Volgograd', 'offset' => '10800'],
            'Kuwait' => ['name' => '(GMT+03:00) Kuwait', 'offset' => '10800'],
            'Riyadh' => ['name' => '(GMT+03:00) Riyadh', 'offset' => '10800'],
            'Nairobi' => ['name' => '(GMT+03:00) Nairobi', 'offset' => '10800'],
            'Baghdad' => ['name' => '(GMT+03:00) Baghdad', 'offset' => '10800'],
            'Abu Dhabi' => ['name' => '(GMT+04:00) Abu Dhabi', 'offset' => '14400'],
            'Muscat' => ['name' => '(GMT+04:00) Muscat', 'offset' => '14400'],
            'Baku' => ['name' => '(GMT+04:00) Baku', 'offset' => '14400'],
            'Tbilisi' => ['name' => '(GMT+04:00) Tbilisi', 'offset' => '14400'],
            'Yerevan' => ['name' => '(GMT+04:00) Yerevan', 'offset' => '14400'],
            'Tehran' => ['name' => '(GMT+04:30) Tehran', 'offset' => '16200'],
            'Kabul' => ['name' => '(GMT+04:30) Kabul', 'offset' => '16200'],
            'Ekaterinburg' => ['name' => '(GMT+05:00) Ekaterinburg', 'offset' => '18000'],
            'Islamabad' => ['name' => '(GMT+05:00) Islamabad', 'offset' => '18000'],
            'Karachi' => ['name' => '(GMT+05:00) Karachi', 'offset' => '18000'],
            'Tashkent' => ['name' => '(GMT+05:00) Tashkent', 'offset' => '18000'],
            'Chennai' => ['name' => '(GMT+05:30) Chennai', 'offset' => '19800'],
            'Kolkata' => ['name' => '(GMT+05:30) Kolkata', 'offset' => '19800'],
            'Mumbai' => ['name' => '(GMT+05:30) Mumbai', 'offset' => '19800'],
            'New Delhi' => ['name' => '(GMT+05:30) New Delhi', 'offset' => '19800'],
            'Sri Jayawardenepura' => ['name' => '(GMT+05:30) Sri Jayawardenepura', 'offset' => '19800'],
            'Kathmandu' => ['name' => '(GMT+05:45) Kathmandu', 'offset' => '20700'],
            'Astana' => ['name' => '(GMT+06:00) Astana', 'offset' => '21600'],
            'Dhaka' => ['name' => '(GMT+06:00) Dhaka', 'offset' => '21600'],
            'Almaty' => ['name' => '(GMT+06:00) Almaty', 'offset' => '21600'],
            'Urumqi' => ['name' => '(GMT+06:00) Urumqi', 'offset' => '21600'],
            'Rangoon' => ['name' => '(GMT+06:30) Rangoon', 'offset' => '23400'],
            'Novosibirsk' => ['name' => '(GMT+07:00) Novosibirsk', 'offset' => '25200'],
            'Bangkok' => ['name' => '(GMT+07:00) Bangkok', 'offset' => '25200'],
            'Hanoi' => ['name' => '(GMT+07:00) Hanoi', 'offset' => '25200'],
            'Jakarta' => ['name' => '(GMT+07:00) Jakarta', 'offset' => '25200'],
            'Krasnoyarsk' => ['name' => '(GMT+07:00) Krasnoyarsk', 'offset' => '25200'],
            'Beijing' => ['name' => '(GMT+08:00) Beijing', 'offset' => '28800'],
            'Chongqing' => ['name' => '(GMT+08:00) Chongqing', 'offset' => '28800'],
            'Hong Kong' => ['name' => '(GMT+08:00) Hong Kong', 'offset' => '28800'],
            'Kuala Lumpur' => ['name' => '(GMT+08:00) Kuala Lumpur', 'offset' => '28800'],
            'Singapore' => ['name' => '(GMT+08:00) Singapore', 'offset' => '28800'],
            'Taipei' => ['name' => '(GMT+08:00) Taipei', 'offset' => '28800'],
            'Perth' => ['name' => '(GMT+08:00) Perth', 'offset' => '28800'],
            'Irkutsk' => ['name' => '(GMT+08:00) Irkutsk', 'offset' => '28800'],
            'Ulaan Bataar' => ['name' => '(GMT+08:00) Ulaan Bataar', 'offset' => '28800'],
            'Seoul' => ['name' => '(GMT+09:00) Seoul', 'offset' => '32400'],
            'Osaka' => ['name' => '(GMT+09:00) Osaka', 'offset' => '32400'],
            'Sapporo' => ['name' => '(GMT+09:00) Sapporo', 'offset' => '32400'],
            'Tokyo' => ['name' => '(GMT+09:00) Tokyo', 'offset' => '32400'],
            'Yakutsk' => ['name' => '(GMT+09:00) Yakutsk', 'offset' => '32400'],
            'Darwin' => ['name' => '(GMT+09:30) Darwin', 'offset' => '34200'],
            'Adelaide' => ['name' => '(GMT+09:30) Adelaide', 'offset' => '34200'],
            'Canberra' => ['name' => '(GMT+10:00) Canberra', 'offset' => '36000'],
            'Melbourne' => ['name' => '(GMT+10:00) Melbourne', 'offset' => '36000'],
            'Sydney' => ['name' => '(GMT+10:00) Sydney', 'offset' => '36000'],
            'Brisbane' => ['name' => '(GMT+10:00) Brisbane', 'offset' => '36000'],
            'Hobart' => ['name' => '(GMT+10:00) Hobart', 'offset' => '36000'],
            'Vladivostok' => ['name' => '(GMT+10:00) Vladivostok', 'offset' => '36000'],
            'Guam' => ['name' => '(GMT+10:00) Guam', 'offset' => '36000'],
            'Port Moresby' => ['name' => '(GMT+10:00) Port Moresby', 'offset' => '36000'],
            'Solomon Is.' => ['name' => '(GMT+10:00) Solomon Is.', 'offset' => '36000'],
            'Magadan' => ['name' => '(GMT+11:00) Magadan', 'offset' => '39600'],
            'New Caledonia' => ['name' => '(GMT+11:00) New Caledonia', 'offset' => '39600'],
            'Fiji' => ['name' => '(GMT+12:00) Fiji', 'offset' => '43200'],
            'Kamchatka' => ['name' => '(GMT+12:00) Kamchatka', 'offset' => '43200'],
            'Marshall Is.' => ['name' => '(GMT+12:00) Marshall Is.', 'offset' => '43200'],
            'Auckland' => ['name' => '(GMT+12:00) Auckland', 'offset' => '43200'],
            'Wellington' => ['name' => '(GMT+12:00) Wellington', 'offset' => '43200'],
            'Nuku\'alofa' => ['name' => '(GMT+13:00) Nuku\'alofa', 'offset' => '46800'],
        ];
    }

    public static function getSampleUserInfo($index = -1)
    {
        $users = [
            [
                'name' => 'Emma Smith',
                'avatar' => 'avatars/300-6.jpg',
                'email' => 'e.smith@kpmg.com.au',
                'position' => 'Art Director',
                'online' => false,
            ],
            [
                'name' => 'Melody Macy',
                'initials' => ['label' => 'M', 'state' => 'danger'],
                'email' => 'melody@altbox.com',
                'position' => 'Marketing Analytic',
                'online' => true,
            ],
            [
                'name' => 'Max Smith',
                'avatar' => 'avatars/300-1.jpg',
                'email' => 'max@kt.com',
                'position' => 'Software Enginer',
                'online' => false,
            ],
            [
                'name' => 'Sean Bean',
                'avatar' => 'avatars/300-5.jpg',
                'email' => 'sean@dellito.com',
                'position' => 'Web Developer',
                'online' => false,
            ],
            [
                'name' => 'Brian Cox',
                'avatar' => 'avatars/300-25.jpg',
                'email' => 'brian@exchange.com',
                'position' => 'UI/UX Designer',
                'online' => false,
            ],
            [
                'name' => 'Mikaela Collins',
                'initials' => ['label' => 'C', 'state' => 'warning'],
                'email' => 'mikaela@pexcom.com',
                'position' => 'Head Of Marketing',
                'online' => true,
            ],
            [
                'name' => 'Francis Mitcham',
                'avatar' => 'avatars/300-9.jpg',
                'email' => 'f.mitcham@kpmg.com.au',
                'position' => 'Software Arcitect',
                'online' => false,
            ],

            [
                'name' => 'Olivia Wild',
                'initials' => ['label' => 'O', 'state' => 'danger'],
                'email' => 'olivia@corpmail.com',
                'position' => 'System Admin',
                'online' => true,
            ],
            [
                'name' => 'Neil Owen',
                'initials' => ['label' => 'N', 'state' => 'primary'],
                'email' => 'owen.neil@gmail.com',
                'position' => 'Account Manager',
                'online' => true,
            ],
            [
                'name' => 'Dan Wilson',
                'avatar' => 'avatars/300-23.jpg',
                'email' => 'dam@consilting.com',
                'position' => 'Web Desinger',
                'online' => false,
            ],
            [
                'name' => 'Emma Bold',
                'initials' => ['label' => 'E', 'state' => 'danger'],
                'email' => 'emma@intenso.com',
                'position' => 'Corporate Finance',
                'online' => true,
            ],
            [
                'name' => 'Ana Crown',
                'avatar' => 'avatars/300-12.jpg',
                'email' => 'ana.cf@limtel.com',
                'position' => 'Customer Relationship',
                'online' => false,
            ],
            [
                'name' => 'Robert Doe',
                'initials' => ['label' => 'A', 'state' => 'info'],
                'email' => 'robert@benko.com',
                'position' => 'Marketing Executive',
                'online' => true,
            ],
            [
                'name' => 'John Miller',
                'avatar' => 'avatars/300-13.jpg',
                'email' => 'miller@mapple.com',
                'position' => 'Project Manager',
                'online' => false,
            ],
            [
                'name' => 'Lucy Kunic',
                'initials' => ['label' => 'L', 'state' => 'success'],
                'email' => 'lucy.m@fentech.com',
                'position' => 'SEO Master',
                'online' => true,
            ],
            [
                'name' => 'Ethan Wilder',
                'avatar' => 'avatars/300-21.jpg',
                'email' => 'ethan@loop.com.au',
                'position' => 'Accountant',
                'online' => true,
            ],
        ];

        $total = count($users);

        if ($index === -1 || isset($users[$index]) === false) {
            $index = rand(0, $total - 1);
        }

        return $users[$index];
    }

    public static function getSampleStatus($index = -1)
    {
        $statuses = [
            ['label' => 'Approved', 'state' => 'success'],
            ['label' => 'Pending', 'state' => 'warning'],
            ['label' => 'Rejected', 'state' => 'danger'],
            ['label' => 'In progress', 'state' => 'info'],
            ['label' => 'Completed', 'state' => 'primary'],
        ];

        $total = count($statuses);

        if ($index === -1 || isset($statuses[$index]) === false) {
            $index = rand(0, $total - 2);
        }

        return $statuses[$index];
    }

    public static function getSampleDate()
    {
        $dates = ['Feb 21', 'Mar 10', 'Apr 15', 'May 05', 'Jun 20', 'Jun 24', 'Jul 25', 'Aug 19', 'Sep 22', 'Oct 25', 'Nov 10', 'Dec 20'];

        $date = $dates[rand(0, count($dates) - 1)].', '.date('Y');

        return $date;
    }

    public static function getSampleDatetime()
    {
        $dates = ['21 Feb', '10 Mar', '15 Apr', '05 May', '20 Jun', '24 Jun', '25 Jul', '19 Aug', '22 Sep', '25 Oct', '10 Nov', '20 Dec'];
        $times = ['8:43 pm', '10:30 am', '5:20 pm', '2:40 pm', '11:05 am', '10:10 pm', '6:05 pm', '11:30 am', '5:30 pm', '9:23 pm', '6:43 am'];

        $date = $dates[rand(0, count($dates) - 1)].' '.date('Y').', '.$times[rand(0, count($times) - 1)];

        return $date;
    }
}
